"""modify updated_ai to updated_at

Revision ID: 2b5dad61052b
Revises: 7bdc1ad370a3
Create Date: 2025-11-15 22:05:00.804135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b5dad61052b'
down_revision: Union[str, Sequence[str], None] = '7bdc1ad370a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('User', 'updated_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('updated_ai', mysql.DATETIME(), nullable=False))
    op.drop_column('User', 'updated_at')
    # ### end Alembic commands ###
